config/routes.rb
CmsinoExample::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root to: 'home#index'
  get 'helps' => "helps#index", as: 'helps'

  # devise_scope :user do
  #   get 'sign_in',  to: 'devise/sessions#new', as: :new_user_session
  #   get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  # end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user 
      can :manage, Cmsino::Content
      can :manage, Cmsino::Medium
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  # :registerable, :recoverable
  devise :omniauthable, :omniauth_providers => [:developer]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Cmsino::ControllerHelpers

  before_action :set_locale

  def set_locale
    if params[:locale] and Cmsino::Conf.instance.locales.include?(params[:locale].to_s)
      session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale || 'it'
  end
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  def index
    # defined in CmsinoHelper 
    # ../gems/cmsino/app/helpers/cmsino_helper.rb
    editable_page(:helps)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # defined in CmsinoHelper 
    # ../gems/cmsino/app/helpers/cmsino_helper.rb
    editable_page(:home)
    @home_header = true
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController  
  skip_before_action :verify_authenticity_token

  def developer
    user = User.first
    sign_in_and_redirect user, event: :authentication  
  end

  def google_oauth2
    logger.info("uid = #{request.env['omniauth.auth'].uid}")
    logger.info("info = #{request.env['omniauth.auth'].info}")

    oinfo = request.env['omniauth.auth'].info

    if user = User.where(email: oinfo.email).first
      sign_in_and_redirect user, event: :authentication    
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include CmsinoHelper
end

app/views/helps/index.html.erb
<h1>Helps</h1>

<%# <%= selectable_image(:main) %1> %>  

<div class="row">
  <div class="span3">
    <%= icon('info-sign') %>  
  </div>
  <div class="span9">
    <h2>who we are</h2>
    <%= editable_content(:who) %>  
  </div>
</div>

app/views/home/_header.html.erb
<div id="home_header_container">
<div id="homeCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#homeCarousel" data-slide-to="1"></li>
    <li data-target="#homeCarousel" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner" role="listbox">
    <div class="item active" style="background: url(<%= image_url('bg/ice.jpg')%>) center center; background-size: cover;"> &nbsp; </div>
    <div class="item" style="background: url(<%= image_url('bg/yellow.jpg')%>) center center; background-size: cover;"> &nbsp; </div>
    <div class="item" style="background: url(<%= image_url('bg/girl.jpg')%>) center center; background-size: cover;"> &nbsp; </div>
  </div>
</div><!-- carousel -->

<div class="container" id="home_header">
  <!-- Left and right controls -->
  <a class="left carousel-control" href="#homeCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#homeCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <h1>
    <span>Example for Cmsino</span> <br/>
    <span>Test</span><br/>
    <div class="home_header_title-date">
      <span><i class="fa fa-calendar"></i> June 5-8, 2018</span><br/> 
      <span><i class="fa fa-map-marker"></i> Bologna - Italy</span>
    </div>
  </h1>
</div><!-- home_header --> 
</div><!-- home_header_container -->

app/views/home/index.html.erb
<p>
<%# defined in CmsinoHelper ../gems/cmsino/app/helpers/cmsino_helper.rb %>
<%= editable_content(:main) %>
</p>

<div class="row home-terzet">
  <div class="col-md-4 centered">
    <h2><i class="fa fa-user-secret" aria-hidden="true"></i></h2>
    <h2>Who</h2>
    <%= editable_content(:who) %>  
  </div>
  <div class="col-md-4 centered">
    <h2><i class="fa fa-calendar" aria-hidden="true"></i></h2>
    <h2>When</h2>
    <%= editable_content(:why) %>  
  </div>
  <div class="col-md-4 centered">
    <h2><i class="fa fa-map-marker" aria-hidden="true"></i></h2>
    <h2>When</h2>
    <%= editable_content(:when) %>  
  </div>
</div>

<div>
  <%= selectable_image(:bg_pedro, style: 'width: 100%', cssclass: 'img-rounded') %>  
</div>

app/views/layouts/_footer.html.erb
<hr/>

app/views/layouts/_menu.html.erb
<header class="navbar navbar-default navbar-main" role="banner">
<div class="container-fluid">
  <div class="navbar-header">
    <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div><!-- navbar-header -->

  <nav class="collapse navbar-collapse" id="bs-navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to 'home', root_path %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to image_tag('it.png'), url_for(locale: :it) %> </li>
      <li><%= link_to image_tag('en.png'), url_for(locale: :en) %> </li>
      <li><%= link_to 'help', helps_path %></li>  

      <% if user_signed_in? %>
        <li><%= link_to current_user.email, '#' %></li>
        <%# <%= link_to "Sign out", destroy_user_session_path, method: :delete %1> %>
        <li><%= link_to "Cmsino", cmsino_pages_path %></li>
      <% else %>
        <li><%= link_to "Sign in", user_developer_omniauth_authorize_path() %></li>
      <% end %>
    </ul>
  </nav>
</div><!-- container -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Description" content="Web page to show the use of Cmsino">
    <title>CmsinoExample</title>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,700italic,700,400italic,300italic,300' rel='stylesheet' type='text/css'>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>script>
    <![endif]-->
  </head>
  <body>
    <%= cmsino_header %>  

    <%= render partial: 'layouts/menu' %>
    <%= render partial: 'home/header' if @home_header %>  

    <div class="container">
      <% if notice %><p class="notice"><%= notice %></p><% end %>
      <% if alert %><p class="alert"><%= alert %></p><% end %>

      <%= editable_content(:hello, :layout) %>  

      <%= yield %>
    </div>

    <%= render partial: 'layouts/footer' %>  
  </body>
</html>